const test = require("node:test");
const assert = require("node:assert/strict");
const bcrypt = require("bcrypt");

// Bezopasan fixture: bcrypt 5, cost 12, javni testni kod "123456".
const BCRYPT_V5_TEST_HASH = "$2b$12$Gn6GJjLhmrNkwJRf8NVRQOz.EPExrYnbEEvSlJ8ph2thmtrPzJe6S";

test("bcrypt accepts a cost-12 hash generated by bcrypt 5", async () => {
  assert.equal(await bcrypt.compare("123456", BCRYPT_V5_TEST_HASH), true);
  assert.equal(await bcrypt.compare("654321", BCRYPT_V5_TEST_HASH), false);
});
